/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EErCpkLNts2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function chatbox() {
  return (
    (<Card className="w-full max-w-md rounded-2xl">
      <CardContent className="p-4 h-[500px] flex flex-col">
        <div className="flex-1 overflow-auto space-y-4 px-2">
          <div className="flex items-start gap-3">
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="bg-muted rounded-lg p-3 max-w-[70%]">
              <p className="text-sm">Hey there! How's it going?</p>
              <div className="text-xs text-muted-foreground mt-1">3:45 PM</div>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-lg p-3 max-w-[70%] text-primary-foreground">
              <p className="text-sm">Pretty good, thanks for asking!</p>
              <div className="text-xs text-primary-foreground/80 mt-1">3:46 PM</div>
            </div>
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AC</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-3">
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="bg-muted rounded-lg p-3 max-w-[70%]">
              <p className="text-sm">Awesome, glad to hear it!</p>
              <div className="text-xs text-muted-foreground mt-1">3:47 PM</div>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-lg p-3 max-w-[70%] text-primary-foreground">
              <p className="text-sm">Yeah, it's been a good day so far.</p>
              <div className="text-xs text-primary-foreground/80 mt-1">3:48 PM</div>
            </div>
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AC</AvatarFallback>
            </Avatar>
          </div>
        </div>
        <div className="mt-4 flex items-center gap-2">
          <Textarea
            placeholder="Type your message..."
            className="flex-1 rounded-lg bg-muted p-2 text-sm" />
          <Button>
            <SendIcon className="w-4 h-4" />
            <span className="sr-only">Send</span>
          </Button>
        </div>
      </CardContent>
    </Card>)
  );
}

function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
